config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
  authenticated :user do
    root 'site#panelcontrol', as: :authenticated_root
  end

  unauthenticated do
    root 'site#home', as: :unauthenticated_root
  end
end


  get '/' => 'site#home'
  get '/contact' => 'site#contact'
  get '/panelcontrol' => 'site#panelcontrol'

  get '/cities/pointsofinterest' => 'point_of_interests#search'
  get '/pointsofinterest' => 'point_of_interests#index'

  resources :cities

end

app/models/city.rb
class City < ActiveRecord::Base

  has_many :point_of_interests

  # validates :name, presence: true
  # validates :name, length: {maximum: 40}
  # validates :name, format: {with: /\A[A-Za-zÑñ\s]+\z/}
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = City.all
  end

  def new
		@city = City.new
	end

  def create
    @city = City.new(entry_params)
    if @city.save
      flash[:notice] = "Entry city successfully"
      redirect_to action: 'index', controller: 'cities'
    else
      flash[:alert] = "Sorry, something went wrong"
      render "new"
    end
  end

  def show
    @city = City.find_by(id: params[:id]) || render_404_(params)
  end

  def edit
    @city = City.find params[:id]
  end

  def update
		#Find the project
		@city = City.find params[:id]
		#update the entry using update_attributes
		if @city.update_attributes(entry_params)
			#If ok redirect_to entries index
			redirect_to action: 'index', controller: 'cities', id: @city.id
		#If wrong show the form again
		else
			render "edit"
		end
  end

  def destroy
    @city = City.find_by(id: params[:id])
    @city.destroy
    redirect_to action:'index', controller: 'cities'
  end

private
	def entry_params
		params.require(:city).permit(:name, :description, :latitude, :longitude)
	end

end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<% if @city.errors.any? %>
	<ul>
		<% @city.errors.full_messages.each do |error_msg|%>
			<li><%= error_msg %></li>
		<% end %>
	</ul>
<% end %>
<%= form_for [@city] do |c| %>
  <div class="field form-group form-singup">
    <%= c.label :name %>
    </br>
  	<%= c.text_field :name, :class=>'form-control text singup' %>
  </div>
  <div class="field form-group form-singup">
	<%= c.label :description %>
  </br>
	<%= c.text_area :description, :class=>'form-control text singup'  %>
	</div>
  <div class="field form-group form-singup">
	<%= c.label :latitude %>
  </br>
	<%= c.text_field :latitude, :class=>'form-control text singup'  %>
	</div>
  <div class="field form-group form-singup">
  <%= c.label :longitude %>
  </br>
	<%= c.text_field :longitude, :class=>'form-control text singup'  %>
	</div>
<div class="field form-group form-singup">
	<%= c.submit 'Save', :class=>'btn btn-info btn-singup' %>
  <%= link_to 'Back', :back %>
</div>
<% end %>

app/views/cities/edit.html.erb
<div class="container">
  <h3>Updating city - <%= @city.name %></h3>
  <%= render 'form' %>
</div>

app/views/cities/index.html.erb
<div class="container showCity">
  <table class="table table-hover">
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
      <% @cities.each do |city| %>
      <tr>
        <td><%= link_to(city.id, city_path(city)) %></td>
        <td><%= link_to(city.name, city_path(city)) %></td>
        <td><%= link_to('Edit', edit_city_path(city.id), class:'btn btn-info btn-singup btn-action') %></td>
        <td><%= link_to('Delete',city_path(city.id), method: 'delete', data:{confirm: 'Are you sure?'}, class:'btn btn-info btn-singup btn-action') %><td>
      </tr>
    <% end %>
  </table>
  <%= link_to('Create new city', new_city_path, class:'btn btn-info btn-singup btn-action')%>
</br>
  <a href="/panelcontrol" class="" type="submit">Go Back</a>
</div>

app/views/cities/new.html.erb
<div class="container">
  <h3>Creating a new city</h3>
  <%= render 'form' %>
</div>

app/views/cities/show.html.erb
	<div class="container showCity">
    <table class="table table-hover">
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Latitude</th>
        <th>Longitude</th>
      </tr>
      <tr>
        <td><%= @city.name%></td>
      	<td><%= @city.description%></td>
        <td><%= @city.latitude%></td>
        <td><%= @city.longitude%></td>
      </tr>
  </table>
  <a href="/cities" class="" type="submit">Back</a>
</div>